checkpointing:
  run_name: "pico-relora-small-test"
  save_to_hf: true
  hf_checkpoint:
    repo_id: pico-relora-small-test
    collection_slug: yuvalw/pico-relora-6766e4e726eb8811626915c0

  learning_dynamics:
    batch_size: 64

monitoring:
  logging:
    log_every_n_steps: 1
  save_to_wandb: true
  wandb:
    entity: pico-lm
    project: pico-relora

model:
    d_model: 384
    activation_hidden_dim: 1536
    relora:
      target_modules: 
        - attention
        - swiglu
      reset_frequency: 2000
      r: 16

training:
  optimization:
    gradient_accumulation_steps: 32

    lr_scheduler: relora_jagged_cosine
    lr_warmup_steps: 2000
    min_lr_ratio: 0.1
    restart_warmup_steps: 100
  
  fabric:
    num_nodes: 1
    num_devices: 4
  
evaluation: 
  metrics: 
    - blimp
    - paloma
  paloma:
    batch_size: 16
  blimp:
    batch_size: 128
